export type ServiceType =
  | "FOOD"
  | "MUSIC"
  | "ART"
  | "DESIGN"
  | "SPACE"
  | "OTHER";

export enum EventType {
  POPUP = "POPUP",
  CONFERENCE = "CONFERENCE",
  CONCERT = "CONCERT",
  DINNER = "DINNER",
  GALA = "GALA",
  FAIR = "FAIR",
  COMPETITION = "COMPETITION",
  CHARITY = "CHARITY",
  NETWORKING = "NETWORKING",
  CELEBRATION = "CELEBRATION",
  OTHER = "OTHER",
}
