import Head from "next/head";

export default function Events() {
  return (
    <>
      <Head>
        <title>Events</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#45df87] to-[#ffffff]"></main>
    </>
  );
}
