export const mcc = 
[
    {"label": "Veterinary", "value": "Veterinary", "mcc": "0742"},
    {"label": "Trade Contractor", "value": "Trade Contractor", "mcc": "1520"},
    {"label": "Taxi/Limo", "value": "Taxi/Limo", "mcc": "4121"},
    {"label": "Tourism", "value": "Tourism", "mcc": "4722"},
    {"label": "Books, Periodicals, and Newspapers", "value": "Books, Periodicals, and Newspapers", "mcc": "5192"},
    {"label": "Variety Stores", "value": "Variety Stores", "mcc": "5331"},
    {"label": "Misc. General Merchandise", "value": "Misc. General Merchandise", "mcc": "5399"},
    {"label": "Grocery / Market", "value": "Grocery / Market", "mcc": "5411"},
    {"label": "Food / Grocery", "value": "Food / Grocery", "mcc": "5499"},
    {"label": "Electric Vehicle Charging", "value": "Electric Vehicle Charging", "mcc": "5552"},
    {"label": "Men's Apparel", "value": "Men's Apparel", "mcc": "5611"},
    {"label": "Apparel", "value": "Apparel", "mcc": "5699"},
    {"label": "Furniture / Home Goods", "value": "Furniture / Home Goods", "mcc": "5712"},
    {"label": "Caterers", "value": "Caterers", "mcc": "5811"},
    {"label": "Restaurant/Bar", "value": "Restaurant/Bar", "mcc": "5812"},
    {"label": "Bar / Club / Lounge", "value": "Bar / Club / Lounge", "mcc": "5813"},
    {"label": "Food Truck / Cart", "value": "Food Truck / Cart", "mcc": "5814"},
    {"label": "Jewelry and Watches", "value": "Jewelry and Watches", "mcc": "5944"},
    {"label": "Other (Japan only)", "value": "Other (Japan only)", "mcc": "5944"},
    {"label": "Art Dealer", "value": "Art Dealer", "mcc": "5971"},
    {"label": "Tobacco", "value": "Tobacco", "mcc": "5993"},
    {"label": "Miscellaneous and Specialty Retail Shops", "value": "Miscellaneous and Specialty Retail Shops", "mcc": "5999"},
    {"label": "Insurance Sales, Underwriting, and Premiums", "value": "Insurance Sales, Underwriting, and Premiums", "mcc": "6300"},
    {"label": "Real Estate", "value": "Real Estate", "mcc": "6513"},
    {"label": "Dry Cleaning and Laundry", "value": "Dry Cleaning and Laundry", "mcc": "7216"},
    {"label": "Beauty / Barber", "value": "Beauty / Barber", "mcc": "7230"},
    {"label": "Dating and Escort Services", "value": "Dating and Escort Services", "mcc": "7273"},
    {"label": "Outdoor Markets", "value": "Outdoor Markets", "mcc": "7278"},
    {"label": "Health and Beauty Spas", "value": "Health and Beauty Spas", "mcc": "7298"},
    {"label": "Personal Services", "value": "Personal Services", "mcc": "7299"},
    {"label": "Web Dev/Design", "value": "Web Dev/Design", "mcc": "7372"},
    {"label": "Tutoring", "value": "Tutoring", "mcc": "7361"},
    {"label": "Consultant", "value": "Consultant", "mcc": "7392"},
    {"label": "Business Services", "value": "Business Services", "mcc": "7399"},
    {"label": "Repair Services", "value": "Repair Services", "mcc": "7699"},
    {"label": "Ticket Sales", "value": "Ticket Sales", "mcc": "7922"},
    {"label": "Membership Clubs / Sports Facilities", "value": "Membership Clubs / Sports Facilities", "mcc": "7997"},
    {"label": "Medical Practitioner", "value": "Medical Practitioner", "mcc": "8011"},
    {"label": "Dentistry", "value": "Dentistry", "mcc": "8021"},
    {"label": "Home Health Care Services", "value": "Home Health Care Services", "mcc": "8082"},
    {"label": "Legal Services", "value": "Legal Services", "mcc": "8111"},
    {"label": "Education", "value": "Education", "mcc": "8244"},
    {"label": "School & Education", "value": "School & Education", "mcc": "8299"},
    {"label": "Charity / Social Services", "value": "Charity / Social Services", "mcc": "8398"},
    {"label": "Political Organizations", "value": "Political Organizations", "mcc": "8651"},
    {"label": "Religious Organizations", "value": "Religious Organizations", "mcc": "8661"},
    {"label": "Membership Org", "value": "Membership Org", "mcc": "8699"},
    {"label": "Accounting", "value": "Accounting", "mcc": "8931"},
    {"label": "Professional Services", "value": "Professional Services", "mcc": "8999"}
];